#! /bin/csh -f
clear

echo -n "What is your heros name?: "
	set character_name = $<
		echo ""
			touch $character_name.txt
mkdir character_profiles
	mv $character_name.txt character_profiles
		cd character_profiles
			echo "name: " | tee -a $character_name.txt
			echo "class: " | tee -a $character_name.txt
			echo "weapon: " | tee -a $character_name.txt
			echo "spell: " | tee -a $character_name.txt
			echo "armor: " | tee -a $character_name.txt
			echo "bag: " | tee -a $character_name.txt
			echo "purse: " | tee -a $character_name.txt			
cd ..

clear

cat class_types.txt
	echo ""
		echo -n "select a character class: "
			set class_type = $<
				cd character_profiles
					sed 's/class: /class: '$class_type'/' $character_name.txt | tee -a 1.0.$character_name.txt
if ( $class_type == mage ) then 
	sed 's/weapon: /weapon: unusible/' 1.0.$character_name.txt | tee -a 2.0.$character_name.txt
  	sed 's/armor: /armor: cloth/' 2.0.$character_name.txt | tee -a 3.0.$character_name.txt
else if ( $class_type == rogue ) then 
	sed 's/spell: /spell: unusible/' 1.0.$character_name.txt | tee -a 2.0.$character_name.txt
    sed 's/armor: /armor: leather/' 2.0.$character_name.txt | tee -a 3.0.$character_name.txt
else if ( $class_type == warrior ) then
	sed 's/spell: /spell: unusible/' 1.0.$character_name.txt | tee -a 2.0.$character_name.txt
	  sed 's/armor: /armor: plate/' 2.0.$character_name.txt | tee -a 3.0.$character_name.txt
endif

cd ..

clear

cat spell_type.txt
	echo ""
		echo -n "Select starting spell type: "
			set spell_type = $<
				cd character_profiles
					sed 's/spell: /spell: '$spell_type'/' 3.0.$character_name.txt | tee -a 4.0.$character_name.txt
					
sed 's/name: /name: '$character_name'/' 4.0.$character_name.txt | tee -a 5.0.$character_name.txt
	sed 's/bag: /bag: empty/' 5.0.$character_name.txt | tee -a 6.0.$character_name.txt
		sed 's/purse: /purse: empty/' 6.0.$character_name.txt | tee -a 7.0.$character_name.txt

cd ..

clear

echo "You are $character_name! A mighty $class_type! SAFE ADVENTURES!"




					
